# Generated by Django 4.1.7 on 2023-03-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idclient', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('dniclient', models.CharField(max_length=9)),
                ('fecnac', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('numserie', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('modelo', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=150)),
                ('precio', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosProvedor',
            fields=[
                ('idproductoprove', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprovedor', models.CharField(max_length=150)),
                ('precio', models.CharField(max_length=150)),
                ('unidades', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idprovedor', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('lolcalizacion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=150)),
                ('product', models.CharField(max_length=150)),
                ('precio', models.CharField(max_length=150)),
                ('unidades', models.CharField(max_length=150)),
            ],
        ),
    ]
