# Generated by Django 4.1.7 on 2023-03-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosprovedor',
            name='nombre',
            field=models.CharField(default='nombre', max_length=150),
        ),
    ]
