# Generated by Django 4.1.7 on 2023-03-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0002_productosprovedor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosprovedor',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
