# Generated by Django 4.1.7 on 2023-03-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0003_alter_productosprovedor_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productosprovedor',
            old_name='idprovedor',
            new_name='provedor',
        ),
    ]
